/**
 * Persist a full CallSummary generated by the agent.
 *
 * Called BY the agent after `regenerate-summary` queued the delegation.
 * The input JSON is validated strictly with Zod — we do not trust the agent
 * to produce a clean shape.
 *
 * Usage (agent-only):
 *   pnpm action write-call-summary --callId=<id> --summary='<json>'
 */

import { defineAction } from "@agent-native/core";
import { z } from "zod";
import { eq } from "drizzle-orm";
import { getDb, schema } from "../server/db/index.js";
import { assertAccess } from "@agent-native/core/sharing";
import { writeAppState } from "@agent-native/core/application-state";

const KeyPointSchema = z.object({
  text: z.string().min(1),
  quoteMs: z.coerce.number().int().min(0).optional(),
});

const NextStepSchema = z.object({
  text: z.string().min(1),
  owner: z.string().optional(),
  dueAt: z.string().optional(),
  quoteMs: z.coerce.number().int().min(0).optional(),
});

const TopicSchema = z.object({
  title: z.string().min(1),
  startMs: z.coerce.number().int().min(0),
  endMs: z.coerce.number().int().min(0).optional(),
});

const QuestionSchema = z.object({
  askedByLabel: z.string().optional(),
  text: z.string().min(1),
  ms: z.coerce.number().int().min(0),
});

const ActionItemSchema = z.object({
  text: z.string().min(1),
  owner: z.string().optional(),
  ms: z.coerce.number().int().min(0).optional(),
});

const SummarySchema = z.object({
  recap: z.string().default(""),
  keyPoints: z.array(KeyPointSchema).default([]),
  nextSteps: z.array(NextStepSchema).default([]),
  topics: z.array(TopicSchema).default([]),
  questions: z.array(QuestionSchema).default([]),
  actionItems: z.array(ActionItemSchema).default([]),
  sentiment: z.enum(["positive", "neutral", "negative"]).optional(),
});

export default defineAction({
  description:
    "Persist a full call summary (recap + keyPoints + nextSteps + topics + questions + actionItems + sentiment). Called by the agent after regenerate-summary. Strictly validates the summary JSON.",
  schema: z.object({
    callId: z.string().describe("Call ID"),
    summary: z
      .union([z.string(), SummarySchema])
      .describe(
        "Full summary object — JSON-encoded string (CLI) or object (agent).",
      ),
  }),
  run: async (args) => {
    await assertAccess("call", args.callId, "editor");

    let parsed: z.infer<typeof SummarySchema>;
    if (typeof args.summary === "string") {
      let raw: unknown;
      try {
        raw = JSON.parse(args.summary);
      } catch (e) {
        throw new Error(`Invalid --summary JSON: ${(e as Error).message}`);
      }
      parsed = SummarySchema.parse(raw);
    } else {
      parsed = SummarySchema.parse(args.summary);
    }

    const db = getDb();
    const nowIso = new Date().toISOString();

    const keyPointsJson = JSON.stringify(parsed.keyPoints);
    const nextStepsJson = JSON.stringify(parsed.nextSteps);
    const topicsJson = JSON.stringify(parsed.topics);
    const questionsJson = JSON.stringify(parsed.questions);
    const actionItemsJson = JSON.stringify(parsed.actionItems);

    const [existing] = await db
      .select({ callId: schema.callSummaries.callId })
      .from(schema.callSummaries)
      .where(eq(schema.callSummaries.callId, args.callId))
      .limit(1);

    if (existing) {
      await db
        .update(schema.callSummaries)
        .set({
          recap: parsed.recap,
          keyPointsJson,
          nextStepsJson,
          topicsJson,
          questionsJson,
          actionItemsJson,
          sentiment: parsed.sentiment ?? null,
          generatedBy: "agent",
          generatedAt: nowIso,
          updatedAt: nowIso,
        })
        .where(eq(schema.callSummaries.callId, args.callId));
    } else {
      await db.insert(schema.callSummaries).values({
        callId: args.callId,
        recap: parsed.recap,
        keyPointsJson,
        nextStepsJson,
        topicsJson,
        questionsJson,
        actionItemsJson,
        sentiment: parsed.sentiment ?? null,
        generatedBy: "agent",
        generatedAt: nowIso,
        updatedAt: nowIso,
      });
    }

    await db
      .update(schema.calls)
      .set({ status: "ready", updatedAt: nowIso })
      .where(eq(schema.calls.id, args.callId));

    await writeAppState("refresh-signal", { ts: Date.now() });

    console.log(`Wrote summary for call ${args.callId}`);
    return {
      callId: args.callId,
      recap: parsed.recap.slice(0, 120),
      keyPoints: parsed.keyPoints.length,
      nextSteps: parsed.nextSteps.length,
      topics: parsed.topics.length,
      questions: parsed.questions.length,
      actionItems: parsed.actionItems.length,
    };
  },
});
